---
title: "Class07 Functions Part 2"
author: "Gidsela Luna"
date: "January 30, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Functions Revisted 
Load(i.e **source**) our rescale() function from last time 
```{r}
source("http://tinyurl.com/rescale-R")
```

```{r}
rescale(1:5)
```

```{r}

#rescale(c(1:5,"string"))

#Error in x - rng[1] : non-numeric argument to binary operator
```

### We want to make this function more robust to these types of errors 
```{r}
#rescale2(c(1:5,"string"))

#Error: Input x should be numeric


```



```{r}
is.numeric(1:5)

```

```{r}
is.numeric("string")
```
```{r}
is.numeric(c(1:5,"string"))
```
```{r}
!is.numeric(c(1:5,"string"))
```

```{r}
!is.numeric(1:5)
```

```{r}

x <- c( 1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)
```

```{r}
is.na(x)
is.na(y)
is.na(x) & is.na(y)==TRUE
```

```{r}
which(is.na(x) & is.na(y) == TRUE)
sum(is.na(x) & is.na(y)==TRUE)
```

```{r}
both_na<- function(x,y){
  #check for the number of NA elements in the vector 
  sum(is.na(x) & is.na(y)==TRUE)
}
```


```{r}
both_na(x,y)
```



```{r}
x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
y3 <- c(1,NA,NA,NA,NA)

#what will this return
both_na(x, y2)



# it is recycling
both_na(x,y3)


```

```{r}
#both_na2(x,y2)

#Error: Input x and y should be vectors of the same length
```


ˆ
```{r}
x <- c( 1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)
both_na3(x,y)
```




